version: 2

project_name: sops-aws-sync

before:
  hooks:
    - go test ./cmd/... ./internal/...

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org

builds:
  - id: sops-aws-sync
    main: ./cmd/sops-aws-sync
    binary: sops-aws-sync
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid=
      - -X main.version={{ .Version }}
      - -X main.commit={{ .FullCommit }}
      - -X main.date={{ .CommitDate }}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: sops-aws-sync
    ids:
      - sops-aws-sync
    formats:
      - binary
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

sboms:
  - id: binary
    artifacts: binary

changelog:
  disable: true

release:
  disable: true
